export const LegalNature = [
    {id: '1015', name: 'Órgão Público do Poder Executivo Federal'},
    {id: '1023', name: 'Órgão Público do Poder Executivo Estadual ou do Distrito Federal'},
    {id: '1031', name: 'Órgão Público do Poder Executivo Municipal'},
    {id: '1040', name: 'Órgão Público do Poder Legislativo Federal'},
    {id: '1058', name: 'Órgão Público do Poder Legislativo Estadual ou do Distrito Federal'},
    {id: '1066', name: 'Órgão Público do Poder Legislativo Municipal'},
    {id: '1074', name: 'Órgão Público do Poder Judiciário Federal '},
    {id: '1082', name: 'Órgão Público do Poder Judiciário Estadual'},
    {id: '1104', name: 'Autarquia Federal'},
    {id: '1112', name: 'Autarquia Estadual ou do Distrito Federal'},
    {id: '1120', name: 'Autarquia Municipal'},
    {id: '1139', name: 'Fundação Pública de Direito Público Federal'},
    {id: '1147', name: 'Fundação Pública de Direito Público Estadual ou do Distrito Federal'},
    {id: '1155', name: 'Fundação Pública de Direito Público Municipal'},
    {id: '1163', name: 'Órgão Público Autônomo Federal'},
    {id: '1171', name: 'Órgão Público Autônomo Estadual ou do Distrito Federal'},
    {id: '1180', name: 'Órgão Público Autônomo Municipal'},
    {id: '1198', name: 'Comissão Polinacional'},
    {id: '1210', name: 'Consórcio Público de Direito Público (Associação Pública)'},
    {id: '1228', name: 'Consórcio Público de Direito Privado'},
    {id: '1236', name: 'Estado ou Distrito Federal'},
    {id: '1244', name: 'Município'},
    {id: '1252', name: 'Fundação Pública de Direito Privado Federal'},
    {id: '1260', name: 'Fundação Pública de Direito Privado Estadual ou do Distrito Federal'},
    {id: '1279', name: 'Fundação Pública de Direito Privado Municipal'},
    {id: '1287', name: 'Fundo Público da Administração Indireta Federal'},
    {id: '1295', name: 'Fundo Público da Administração Indireta Estadual ou do Distrito Federal'},
    {id: '1309', name: 'Fundo Público da Administração Indireta Municipal'},
    {id: '1317', name: 'Fundo Público da Administração Direta Federal'},
    {id: '1325', name: 'Fundo Público da Administração Direta Estadual ou do Distrito Federal'},
    {id: '1333',name: 'Fundo Público da Administração Direta Municipal'},
    {id: '1341',name: 'União'},
    {id: '2011',name: 'Empresa Pública'},
    {id: '2038',name: 'Sociedade de Economia Mista'},
    {id: '2046',name: 'Sociedade Anônima Aberta'},
    {id: '2054',name: 'Sociedade Anônima Fechada'},
    {id: '2062',name: 'Sociedade Empresária Limitada'},
    {id: '2070',name: 'Sociedade Empresária em Nome Coletivo'},
    {id: '2089',name: 'Sociedade Empresária em Comandita Simples'},
    {id: '2097',name: 'Sociedade Empresária em Comandita por Ações'},
    {id: '2127',name: 'Sociedade em Conta de Participação'},
    {id: '2135',name: 'Empresário (Individual)'},
    {id: '2143',name: 'Cooperativa'},
    {id: '2151',name: 'Consórcio de Sociedades'},
    {id: '2160',name: 'Grupo de Sociedades'},
    {id: '2178',name: 'Estabelecimento, no Brasil, de Sociedade Estrangeira'},
    {id: '2194',name: 'Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira'},
    {id: '2216',name: 'Empresa Domiciliada no Exterior'},
    {id: '2224',name: 'Clube/Fundo de Investimento'},
    {id: '2232',name: 'Sociedade Simples Pura'},
    {id: '2240',name: 'Sociedade Simples Limitada'},
    {id: '2259',name: 'Sociedade Simples em Nome Coletivo'},
    {id: '2267',name: 'Sociedade Simples em Comandita Simples'},
    {id: '2275',name: 'Empresa Binacional'},
    {id: '2283',name: 'Consórcio de Empregadores'},
    {id: '2291',name: 'Consórcio Simples'},
    {id: '2305',name: 'Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)'},
    {id: '2313',name: 'Empresa Individual de Responsabilidade Limitada (de Natureza Simples)'},
    {id: '2321',name: 'Sociedade Unipessoal de Advogados'},
    {id: '2330',name: 'Cooperativas de Consumo'},
    {id: '2348',name: 'Empresa Simples de Inovação - Inova Simples'},
    {id: '2356', name: 'Investidor Não Residente'}
]