export const VALIDTOKEN = "VALID TOKEN";

export const HEADERMENUITEMCLICKED = "HEADER MENU ITEM CLICKED";

export const iTEMONMOUSEOVER = "iTEM ON MOUSE OVER";

export const iTEMONMOUSEOUT = "iTEM ON MOUSE OUT";

export const OPENMODAL = "OPEN MODAL";

export const CLOSEMODAL = "CLOSE MODAL";

export const SETJOBLIST = "SET JOB LIST";

export const SETSTATUSLIST = "SET STATUS LIST";

export const SETPROJECTTYPELIST = "SET PROJECT TYPE LIST";

export const SETPROJECTLIST = "SET PROJECT LIST";

export const JOBOPTIONCLICKED = "JOB OPTION CLICKED";

export const STATUSOPTIONCLICKED = "STATUS OPTION CLICKED"

export const MODALEDITOPEN = "MODAL EDIT OPEN";

export const MODALREGISTEROPEN = "MODAL REGISTER OPEN"

export const EDITJOBCLICKED = "EDIT JOB CLICKED"

export const EDITSTATUSCLICKED = "EDIT STATUS CLICKED"

export const EDITPROJECTTYPECLICKED = "EDIT PROJECT TYPE CLICKED"

export const PROJECTTYPEOPTIONCLICKED = "PROJECT TYPE OPTION CLICKED"

export const PROJECTOPTIONCLICKED = "PROJECT OPTION CLICKED"

export const OCCUPATIONOPTIONCLICKED = "OCCUPATION OPTION CLICKED"

export const SETOCCUPATIONLIST = "SET OCCUPATION LIST"

export const EDITOCCUPATIONCLICKED = "EDIT OCCUPATION CLICKED"

export const SETSETTINGSPAGES = "SET SETTINGS PAGES"

export const SETSEARCHNAME = "SET SEARCH NAME"

export const SETFILTERSTATUS = "SET FILTER STATUS"

export const RESETCURRENTPAGE = "RESET CURRENT PAGE"

export const RESETFILTERSTATUS = "RESET FILTER STATUS"

export const SETFILTERORDER = "SET FILTER ORDER"

export const SETPROJECTSPAGES = "SET PROJECTS PAGES"

export const SETSEARCHNAMEPROJECT = "SET SEARCH NAME PROJECT"

export const RESETCURRENTPAGEPROJECT = "RESET CURRENT PAGE PROJECT"

export const SETFILTERORDERPROJECTS = "SET FILTER ORDER PROJECTS"

export const SETFILTERSTATUSPROJECTS = "SET FILTER STATUS PROJECTS"

export const RESETFILTERSTATUSPROJECTS = "RESET FILTER STATUS"

export const SETSTATUSCOLORS = "SET STATUS COLORS"

export const SETSTATUSLISTPROJECTS = "SET STATUS LIST PROJECTS";

export const SETPROJECTTYPELISTPROJECTS = "SET PROJECT TYPE LIST PROJECTS";

export const SETFILTERTYPESPROJECTS = "SET FILTER TYPESPROJECTS"

export const RESETFILTERTYPESPROJECTS = "RESET FILTER TYPES PROJECTS"

export const SETPROJECTLISTPROJECTS = "SET PROJECT LIST";



