export const VALIDTOKEN = "VALID TOKEN";

export const MENUSTATUS = "MENU STATUS";

export const HEADERMENUITEMCLICKED = "HEADER MENU ITEM CLICKED";

export const iTEMONMOUSEOVER = "iTEM ON MOUSE OVER";

export const iTEMONMOUSEOUT = "iTEM ON MOUSE OUT";

export const OPENMODAL = "OPEN MODAL";

export const CLOSEMODAL = "CLOSE MODAL";

export const SETJOBLIST = "SET JOB LIST";

export const JOBOPTIONCLICKED = "JOB OPTION CLICKED";

export const MODALEDITOPEN = "MODAL EDIT OPEN";

export const MODALREGISTEROPEN = "MODAL REGISTER OPEN"

export const EDITJOBCLICKED = "EDIT JOB CLICKED"
